version: '3'

services:
  sshd:
    build: ./docker/sshd/
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
  capistrano:
    build: ./docker/capistrano/
    working_dir: /home/app/
    volumes:
      - ./:/home/app/
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
